version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "uv"
    directory: "/core"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" 
    directory: "/ui" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "jasmine-core"
        update-types: ["version-update:semver-major"]
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "zone.js"
