"""Password and API key hashing in `learninghouse.models.auth`, see
docs/decisions/0006-argon2id-passwords-and-hashed-api-keys.md.

Passwords are argon2id, API keys a salted SHA-256.

`_security_filename` is patched per test: `SecurityDatabase.write()` resolves
it through the process-wide settings otherwise, and these tests deliberately
write the database to disk.
"""

import pytest

from learninghouse.models.auth import (
    API_KEY_BYTES,
    API_KEY_HASH_PREFIX,
    APIKeyRequest,
    APIKeyRole,
    SecurityDatabase,
)


@pytest.fixture()
def security_file(tmp_path, monkeypatch):
    filename = tmp_path / "security.json"
    monkeypatch.setattr(
        "learninghouse.models.auth._security_filename", lambda: filename
    )
    return filename


class TestPasswordHashing:
    def test_a_new_database_hashes_the_fallback_password_with_argon2(
        self, security_file
    ):
        database = SecurityDatabase.load_or_write_default()

        assert database.admin_password.startswith("$argon2")
        assert database.authenticate_password("learninghouse") is True

    def test_a_wrong_password_is_rejected(self, security_file):
        database = SecurityDatabase.load_or_write_default()

        assert database.authenticate_password("not-the-password") is False

    def test_an_updated_password_is_stored_as_argon2(self, security_file):
        database = SecurityDatabase.load_or_write_default()

        database.update_password("a-new-password")

        assert database.admin_password.startswith("$argon2")
        assert database.initial_password is False
        assert database.authenticate_password("a-new-password") is True


class TestApiKeyHashing:
    def test_a_created_key_is_stored_as_a_salted_sha256(self, security_file):
        database = SecurityDatabase.load_or_write_default()

        created = database.create_apikey(
            APIKeyRequest(description="app_as_user", role=APIKeyRole.USER)
        )

        stored = list(database.api_keys)
        assert len(stored) == 1
        assert stored[0].startswith(API_KEY_HASH_PREFIX)
        # The raw key is returned once and never stored.
        assert created.key not in stored

    def test_a_created_key_is_found_again(self, security_file):
        database = SecurityDatabase.load_or_write_default()
        created = database.create_apikey(
            APIKeyRequest(description="app_as_user", role=APIKeyRole.USER)
        )

        found = database.find_apikey_by_key(created.key)

        assert found is not None
        assert found.description == "app_as_user"

    def test_an_unknown_key_is_not_found(self, security_file):
        database = SecurityDatabase.load_or_write_default()
        database.create_apikey(
            APIKeyRequest(description="app_as_user", role=APIKeyRole.USER)
        )

        assert database.find_apikey_by_key("00000000000000000000000000000000") is None


class TestApiKeyEntropy:
    """The condition the API key hashing rests on.

    A salted SHA-256 is the right construction for a key of 128 random bits
    generated by the service, and the wrong one for a secret a person may
    choose. Neither half of that is enforced by the hashing code itself, so
    it is enforced here: if a future change lets a client bring its own key,
    or shortens the generated one, these tests fail and the hash choice has
    to be revisited (docs/decisions/0006-argon2id-passwords-and-hashed-api-
    keys.md).
    """

    def test_a_generated_key_carries_at_least_128_bits(self, security_file):
        database = SecurityDatabase.load_or_write_default()

        created = database.create_apikey(
            APIKeyRequest(description="app_as_user", role=APIKeyRole.USER)
        )

        assert API_KEY_BYTES >= 16
        assert len(bytes.fromhex(created.key)) == API_KEY_BYTES

    def test_two_keys_are_not_the_same(self, security_file):
        database = SecurityDatabase.load_or_write_default()

        first = database.create_apikey(
            APIKeyRequest(description="app_as_user", role=APIKeyRole.USER)
        )
        second = database.create_apikey(
            APIKeyRequest(description="app_as_trainer", role=APIKeyRole.TRAINER)
        )

        assert first.key != second.key

    def test_a_client_cannot_choose_its_own_key(self):
        # The request model carries no key field, so there is no route by
        # which a caller-supplied secret reaches hash_api_key.
        assert "key" not in APIKeyRequest.model_fields
